---
title: "Linear Regression"
output: github_document
---

```{r setup,include=FALSE}
library(tidyverse)
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp =0.6,
  out.width = "90%"
) 

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

```

```{r}
library(tidyverse)
library(p8105.datasets)

set.seed(1)

```

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(
    borough = neighbourhood_group,
    neighborhood = neighbourhood) %>% 
  filter(borough != "Staten Island") %>% 
  select(price, stars, borough, neighborhood, room_type)
```

## Fit a model
Price is the outcome,depending on stars and borough
```{r}
fit = lm(price ~ stars + borough, data = nyc_airbnb)
```

Let's look at the result..
```{r,include = FALSE}
summary(fit)
summary(fit)$coefficient
coef(fit)
residuals(fit)
```

```{r}
broom::glance(fit)
broom::tidy(fit) %>% 
  select(-std.error,-statistic) %>% 
  mutate(term = str_replace(term,"borough","Borough:")) %>% 
  knitr::kable(digits = 3)

```


## Be in control of factors 
```{r}
nyc_airbnb =
  nyc_airbnb %>% 
  mutate(
    borough=fct_infreq(borough),
    room_type=fct_infreq(room_type)
  )
```


Look at that plot again
```{r}
nyc_airbnb %>% 
  ggplot(aes(x=stars,y=price,color=borough)) + geom_point()
  
```

```{r}
fit = lm(price ~ stars + borough, data = nyc_airbnb)
broom::tidy(fit)
broom::glance(fit)
```

## Diagnostics
ylim = y limit
facet_wrap =multiple panels
```{r}
nyc_airbnb %>% 
modelr::add_residuals(fit) %>% 
  ggplot(aes(x=borough,y=resid))+
  geom_violin()+
  ylim(-500,1500)

nyc_airbnb %>% 
  modelr::add_residuals(fit) %>% 
  ggplot(aes(x=stars,y=resid))+
  geom_point()+
  facet_wrap(.~borough)
```

## Hypothesis tests
This does t-test by default
```{r}
fit %>% 
  broom::tidy()
```

what about the significance of `borough`

```{r}
fit_null = lm(price ~ stars,data=nyc_airbnb)
fit_alt=lm(price~stars+borough,data=nyc_airbnb)
anova(fit_null,fit_alt) %>% 
  broom::tidy()

```


